version: "3.8"
services:
  storage:
    container_name: storage
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=celery_results
    ports:
      - 5432:5432
  message-broker:
    container_name: rabbit
    image: rabbitmq
    ports:
      - 5672:5672
  scheduler:
    privileged: true
    depends_on:
      - "message-broker"
      - "storage"
    build:
      context: workers
      args: 
        NAME: scheduler
    command: celery -A project.application beat -l DEBUG
  requester:
    privileged: false
    depends_on:
      # - "scheduler"
      - "message-broker"
      - "storage"
    build:
      context: workers
      args: 
        NAME: requester