version: "3.8"
services:
  storage:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=celery_results
    ports:
      - 5432:5432
  message-broker:
    image: rabbitmq
    ports:
      - 5672:5672
  zookeeper1:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
      - '2888'
      - '3888'
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
  zookeeper2:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
      - '2888'
      - '3888'
    environment:
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper1:2888:3888,0.0.0.0:2888:3888,zookeeper3:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
  zookeeper3:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
      - '2888'
      - '3888'
    environment:
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,0.0.0.0:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
  scheduler:
    depends_on:
      - "message-broker"
      - "storage"
      - "zookeeper1"
      - "zookeeper2"
      - "zookeeper3"
    image: celery-worker
    command: celery -A project.application beat -l DEBUG
  requester:
    depends_on:
      - "scheduler"
    image: celery-worker
    environment: 
      TASK_NAME: '{{.Task.Name}}'
    user: "1"
    command: ["/bin/sh", "/project/entrypoint.sh"]
    deploy:
      replicas: 3
  result-shard:
    depends_on:
      - scheduler
    image: postgres-shard
    environment: 
      TASK_NAME: '{{.Task.Name}}'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: process_results
  test:
    image: testing-proxy
    ports:
      - target: 80
        published: 80
    depends_on:
      - scheduler
  